"""Long-form OpenAPI/Swagger documentation text for LTX-2.5's own endpoints,
kept out of router.py so the routes themselves stay readable. Docs shared
by every backend (uploads, jobs, app-level description) live in
common/openapi_docs.py instead.

This is the machine-readable half of LTX-2.5's docs, meant to be read via
/openapi.json or /docs. The companion services/ltx25/GUIDE.md (same
directory, folded into GET /v1/guide's own LTX-2.5 section at request time)
is the prose half -- the model, prompting technique (including multi-shot),
and operational quirks that a schema alone can't capture.
"""

from __future__ import annotations

GENERATE_VIDEO = """
Text-to-video, or image-to-video if you attach one or more `images`, on LTX-2.5.

**Two recipes, chosen by `mode`:**
- `"fast"` (default) -- the distilled pipeline: a fixed 8-step schedule with no guidance.
  Fastest and cheapest.
- `"quality"` -- the DFR (Diffusion Fidelity Rendering) pipeline: the same distilled
  transformer, plus extra generated keyframes at half resolution and a second-stage
  detailing pass at full resolution. Sharper detail than `"fast"`; slower, and needs more
  GPU memory.

There is no `negative_prompt` field: both LTX-2.5 recipes run without guidance, so there is
nothing for one to act on.

**Clip length.** Use `duration_seconds` or `num_frames` as usual (default ~5s), or set
`auto_duration: true` to let the model predict the length from the prompt (clamped to
1-20 seconds). `auto_duration` cannot be combined with `duration_seconds` or `num_frames`.

**Multi-shot.** LTX-2.5 can cut between 2-4 shots inside one clip, holding the same
character, lighting, and voice across the cuts. There is no parameter for it -- you write the
cuts into the `prompt` in prose. See `GET /v1/guide` for how.

Output: MP4, H.264 video + AAC audio, muxed together. Video and audio are generated
*jointly* by the same model -- quoted dialogue in the prompt comes out lip-synced.

`images[].frame_idx == 0` makes that image the literal first frame (true image-to-video);
`frame_idx > 0` uses it as keyframe guidance partway through instead.
"""

INTERPOLATE = """
Generates a video that starts on `first_frame_asset_id` and ends on `last_frame_asset_id`,
with `prompt` describing the motion that connects them -- first/last-frame interpolation on
LTX-2.5. Upload both images first with `POST /v1/uploads`.

**Two recipes, chosen by `mode`**, with the same meaning as on
`POST /v1/ltx25/videos/generate`: `"fast"` (default, the distilled pipeline) and `"quality"`
(the DFR pipeline: sharper detail, slower, more GPU memory). There is no `negative_prompt`.

**How the frames are used.** The first image is placed at frame 0 and becomes the literal first
frame of the video. The last image is placed at the final frame and guides the video's ending, so
the clip lands on it. The video's length comes from `duration_seconds` or `num_frames` (default
~5s); a longer clip gives the model more time to travel between the two frames.

**Choosing the two frames.** Interpolation works best when both frames come from the same scene
(same place, subject, and lighting) and the change between them is a plausible movement or
action. When the two frames are completely different compositions (for example, a wide shot of a
courtyard and a close-up of a person), the model cannot invent a physical camera move between
them and tends to produce a cross-dissolve -- a ghosted blend of the two images -- in the middle
of the clip. It still starts and ends exactly on your frames either way.

**Image shape.** Both images are resized and center-cropped to the output size, so give them the
same aspect ratio as the output (16:9 for `landscape`, 9:16 for `portrait`) to avoid unwanted
cropping. There is no `auto_duration` on this endpoint: the last frame's position depends on
knowing the length up front.

Output: MP4, H.264 video + AAC audio, muxed together. Audio is generated by the model to match
the motion; it is not carried over from the images (which have none).
"""

RETAKE = """
Regenerates only the `[start_time, end_time]` window of an existing video on LTX-2.5.
Both video and audio inside the window are regenerated together, driven by `prompt`; the rest
of the video is left visually the same. The whole clip is re-encoded, so frames outside the
window are very close to the source but not bit-for-bit identical.

**Distilled checkpoint only** -- the only variant the underlying pipeline ships.

**The source video must already satisfy the model's own shape constraints.** This is not
checked by this API -- a video that doesn't will fail only once the job is already running on
a GPU: frame count must be `8k+1` (97, 121, 193, ...) and width/height must each be a multiple
of 32. A video produced by `POST /v1/ltx25/videos/generate` already satisfies this.

There are no `height`/`width`/`num_frames`/`orientation` fields on this endpoint: the output
always matches the source video's resolution, frame count, and frame rate exactly.
"""

# ---------------------------------------------------------------------------
# Named request-body examples (Swagger's "Examples" dropdown per endpoint)
# ---------------------------------------------------------------------------

GENERATE_VIDEO_EXAMPLES = {
    "fast_landscape": {
        "summary": "Fast mode, landscape, 5s -- good default for iterating",
        "value": {
            "prompt": (
                "A golden retriever puppy runs across a sunlit lawn, tongue out, tail wagging, "
                "chasing a bright yellow tennis ball. Bright daylight, shallow depth of field, "
                "handheld camera following the puppy."
            ),
            "mode": "fast",
            "orientation": "landscape",
            "duration_seconds": 5,
            "seed": 42,
        },
    },
    "quality_dfr": {
        "summary": "Quality mode (DFR) for a final take",
        "value": {
            "prompt": (
                "A chef in a white uniform plates a dessert in a busy restaurant kitchen, steam "
                "rising from the pan behind her, camera slowly pushing in."
            ),
            "mode": "quality",
            "orientation": "landscape",
            "duration_seconds": 5,
        },
    },
    "multi_shot": {
        "summary": "Multi-shot: three cuts written into one prompt",
        "value": {
            "prompt": (
                "A wide shot establishes a rainy courtyard at dusk, a woman in a yellow raincoat "
                "standing under a lamp as soft piano music plays. A hard cut transitions to a "
                "close-up of the woman in the yellow raincoat, raindrops on her face, as she says "
                'quietly, "He said he would be here." The piano continues across the cut. A match '
                "cut connects to a low-angle shot of her boots in a puddle as the music drops to a "
                "low drone."
            ),
            "mode": "fast",
            "orientation": "landscape",
            "duration_seconds": 10,
        },
    },
    "auto_duration": {
        "summary": "Let the model choose the clip length",
        "value": {
            "prompt": (
                "A paper boat drifts down a rain-filled gutter, bobbing over small ripples, as "
                "the camera tracks alongside at water level."
            ),
            "mode": "fast",
            "orientation": "landscape",
            "auto_duration": True,
        },
    },
    "image_to_video": {
        "summary": "Image-to-video: animate an uploaded photo as the first frame",
        "value": {
            "prompt": (
                'The man in the photo turns his head slowly to look directly at the camera and '
                'says, "I think it\'s ready." Soft natural light, shallow depth of field.'
            ),
            "mode": "fast",
            "orientation": "landscape",
            "duration_seconds": 5,
            "images": [{"asset_id": "<asset_id from POST /v1/uploads>", "frame_idx": 0, "strength": 1.0}],
        },
    },
}

INTERPOLATE_EXAMPLES = {
    "fast_first_to_last": {
        "summary": "Fast mode: interpolate from a start frame to an end frame",
        "value": {
            "prompt": (
                "A flower blooms from a tight bud into a fully open blossom in a smooth, "
                "continuous motion, soft natural light, shallow depth of field."
            ),
            "first_frame_asset_id": "<asset_id of the starting frame>",
            "last_frame_asset_id": "<asset_id of the ending frame>",
            "mode": "fast",
            "orientation": "landscape",
            "duration_seconds": 5,
        },
    },
    "quality_longer": {
        "summary": "Quality mode, longer clip for a bigger change between the frames",
        "value": {
            "prompt": (
                "The camera slowly pulls back as the city transitions from dawn to full "
                "daylight, traffic gradually filling the streets below."
            ),
            "first_frame_asset_id": "<asset_id of the starting frame>",
            "last_frame_asset_id": "<asset_id of the ending frame>",
            "mode": "quality",
            "orientation": "landscape",
            "duration_seconds": 8,
        },
    },
}

RETAKE_EXAMPLES = {
    "regenerate_a_window": {
        "summary": "Replace the 2.0s-4.0s window of an existing video",
        "value": {
            "video_asset_id": "<asset_id of the source video>",
            "prompt": "The man raises his coffee cup and takes a slow sip, then sets it back down on the table.",
            "start_time": 2.0,
            "end_time": 4.0,
        },
    },
}
